version: '3.3'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=zabbix
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=zabbix
      # You can use whatever password you like
      - MYSQL_PASSWORD=123456
      # Password for root access
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
  
  
  # CREATE USER 'zabbix'@'localhost' IDENTIFIED BY '123456';
  # GRANT ALL PRIVILEGES ON zabbix.* TO 'zabbix'@'localhost';
  # FLUSH PRIVILEGES;
# GRANT ALL PRIVILEGES ON *.* TO 'zabbix'@'%' IDENTIFIED BY '12345678' WITH GRANT OPTION;
