version: '3'

services:
  php73:
    image: php:7.3-apache
    ports:
      - 80:80
    networks:
      - bridge_network
    volumes:
        - ./:/var/www/html/

networks:
  bridge_network:
    driver: bridge
