 
version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9002:9001
    networks:
      - minionetwork
    volumes:
      - ./minio_storage:/data
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=passminio
      - MINIO_DEFAULT_BUCKETS=minio
      #- MINIO_SERVER_URL=<host>:9000 #ip do host Minio
      #- MINIO_BROWSER_REDIRECT_URL=<host>:9002
    command: server --console-address ":9001" /data  

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
